name: ecosed_kit
description: "EcosedKit"
version: 0.0.1
homepage:
environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_plugin_android_lifecycle: ^2.0.17
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: io.ecosed.ecosed_kit
        pluginClass: EcosedKitPlugin